#ifndef UPS_API_LIBRARY_GLOBAL_H
#define UPS_API_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPS_API_LIBRARY_LIBRARY)
#define UPS_API_LIBRARY_EXPORT Q_DECL_EXPORT
#else
#define UPS_API_LIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // UPS_API_LIBRARY_GLOBAL_H
